---
- name: Overwrite hostname config
  template: src=hostname.j2 dest=/etc/mesos-slave/hostname

- name: Turn on slave checkpoint
  shell: touch /etc/mesos-slave/checkpoint
  when: mesos_slave_checkpoint == "yes"

- name: Support Docker containerizers
  shell: echo 'docker,mesos' > /etc/mesos-slave/containerizers
  when: mesos_docker_support == "yes"

# == Delete to force template creation
- name: Delete slave script
  file: path=/etc/init/mesos-slave.conf state=absent

- name: Overwrite mesos-slave init script
  template: src=mesos-slave.j2 dest=/etc/init/mesos-slave.conf
  notify:
    - Restart mesos-slave

